version: "3"
services:
  grafana:
    container_name: grafana
    user: grafana:root
    image: grafana/grafana-oss:main
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - grafana:/var/lib/grafana/
    - grafana-plugins:/var/lib/grafana/plugins/
    - grafana-datasources:/etc/grafana/datasources/
    - grafana-dashboards:/etc/grafana/dashboards/
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=123987
  prometheus:
    container_name: prometheus
    image: prom/prometheus:main
    restart: always
    ports:
    - "9090:9090"
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - etc-prometheus:/etc/prometheus/
    - prometheus:/prometheus
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:master
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    ports:
      - 9100:9100
    restart: always
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    restart: always

volumes:
  prometheus:
  etc-prometheus:
  grafana:
  grafana-plugins:
  grafana-datasources:
  grafana-dashboards:
